### PR TITLE
Solved feature frontend

### LINKED ISSUE #8: User Story 2: Display the solved status on the frontend
**Description:** Update UI to visually indicate when a question is marked as solved, and provide the original poster with a button to mark/unmark it.

**Estimated Effort:** Medium

**Dependencies:** Backend API must be completed for status updates.

**Acceptance Criteria:** "Solved" button appears for original poster only.
Solved questions show a "solved" tag and changes are reflected correctly and responsive.

### LINKED ISSUE #9: User Story 2: Testing Full Solved Button Feature
**Description:** Ensure the "mark as solved" feature works correctly from backend to frontend, and that unit tests cover the core functionality.

**Estimated Effort:** Medium

**Dependencies:** Backend and frontend tasks must be completed.
**Acceptance Criteria:**

1. Original poster can successfully mark/unmark questions as "solved."
2. "Solved" questions are visually distinguished from unsolved ones.
3. Tests verify that the feature works end-to-end.

### PR DESCRIPTION
**Pull request by Nalseaf**
**Summary of Changes:** This pull request introduces an enhancement to the composer theme interface by adding an option for users to mark a question as solved. The following modifications were made to the templates/partials/topic/post.tpl file:

**Mark As Solved Button:**

Added a button called "Mark As Solved" alongside other buttons on a post. This allows users to mark a question as solved after posting a question/ comment 

The button is placed logically within the action bar, making it easily accessible to users while they edit their posts.

**Next steps:**
**Integration** with Existing Functionality:
The button will be used to determine whether the user’s marked a question as solved or not. This functionality will be handled in the corresponding JavaScript logic to ensure proper processing in the backend.

**Fixes #8** 

An image showing where the button should be **located** and how it looks when **clicked**:
Screenshot 2024-10-09 at 10 03 13 PM

An image showing how the button looks when **not clicked**:
Screenshot 2024-10-09 at 10 03 09 PM

### CODE REVIEW

**Review by mthani2 — APPROVED** [review]
Looks good to me! Great job.

**Comment by sarrakhelifi-cmu** [comment]
Great job I think everything sounds good.

**Review by sarrakhelifi-cmu — COMMENTED** [review]
Great job, I see what you did. It should be fine.

**Review by sarrakhelifi-cmu — APPROVED** [review]

**Comment by T7alabdullah** [comment]
Looks perfect! Should be good to go

**Pull request merged**
