### PR TITLE
Anonymous posting frontend

### LINKED ISSUE #3: User Story 1: Add Anonymity Option (Button) to Post Creation Form
**Description:** Modify the post creation form to include an option for students to select anonymity when posting a question.

**Estimated Effort:** Medium

**Dependencies:** Requires changes to the frontend to integrate with the backend.

**Acceptance Criteria:** The post creation form should have a checkbox or toggle for anonymity. When selected, the post should be marked as anonymous in the system.

### LINKED ISSUE #20: User Story 1: Resolve gitignore Issue for nodebb-plugin-composer-default
**Description:** The nodebb-plugin-composer-default folder is currently being ignored by Git, preventing important changes from being tracked in the repository. This issue aims to update the .gitignore file to allow tracking of this folder, enabling collaborative development on the composer plugin.

**Estimated Effort:** Medium-high

**Dependencies:** None

**Acceptance Criteria:**
- The .gitignore file is updated to include an exception for nodebb-plugin-composer-default.
- Changes made to the nodebb-plugin-composer-default folder can be tracked by Git.

### PR DESCRIPTION
**Pull request by mthani2**
**Summary of Changes:** This pull request introduces an enhancement to the composer interface by adding an option for users to post anonymously. The following modifications were made to the composer-title-container.tpl file:

**Anonymous Checkbox:**
- Added a checkbox labeled "Post anonymously" within the action bar of the composer. This allows users to select anonymity when composing messages.
- The checkbox has been implemented using Bootstrap classes for consistent styling and responsiveness.
Placement:
- The checkbox is placed logically within the action bar, making it easily accessible to users while they compose their messages.

**Next steps:
Integration with Existing Functionality:**
The checkbox will be used to determine whether the user’s identity should be included when a message is sent. This functionality will be handled in the corresponding JavaScript logic to ensure proper processing in the backend.

Fixes https://github.com/CMU-17313Q/nodebb-f24-team-pawsitive/issues/3
An image showing where the button should be located and how it looks when clicked:
Screenshot 2024-09-25 at 9 44 16 PM

An image showing how the button looks when not clicked:
Screenshot 2024-09-25 at 9 45 06 PM

### CODE REVIEW

**Comment by mthani2** [comment]
Github shows 0 file changes and when tested we could not pull the node_modules file changes, this suggests a new issue: the gitIgnore file isn't allowing Github to access the file changes made under node_modules.

Must be fixed: #20

**Comment by mthani2** [comment]
> Github shows 0 file changes and when tested we could not pull the node_modules file changes, this suggests a new issue: the gitIgnore file isn't allowing Github to access the file changes made under node_modules.
> 
> Must be fixed: #20

Fixed #20 by editing gitIgnore file.
This was the change made to the gitIgnore file: 
Screenshot 2024-09-25 at 9 47 10 PM

**Comment by Nalseaf** [comment]
Looks Good To Me!!

**Review by Nalseaf — COMMENTED** [review]
Looks Good To Me!!

**Review by sarrakhelifi-cmu — COMMENTED** [review]
LGTM! I think we will make future adjustments to this file based on backend and db.

**Pull request merged**
